import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { PanelProps } from '@grafana/data';
import { locationService } from '@grafana/runtime';
import { buildDetectorGeometry } from '../geometry/buildGeometry';
import { geometryFromJson } from '../geometry/config';
import { DetectorScene } from '../geometry/DetectorScene';
import { mapMeasurementsToModules } from '../data/measurements';
import {
  CameraMode,
  HoveredModule,
  InnerTracker3DOptions,
  ModuleDescriptor,
  ModuleMeasurement,
  VisibilityState,
} from '../types';
import { defaultVisibility, VisibilityTree } from './VisibilityTree';
import { Tooltip } from './Tooltip';
import { DEFAULT_OPTIONS } from '../defaults';
import { effectiveRegisterLimit, REGISTER_LIMITS } from '../data/registerLimits';
import './panel.css';

const VISIBILITY_KEY = 'cmsit-inner-tracker-3d:visibility';

function loadVisibility(remember: boolean): VisibilityState {
  if (!remember) {
    return defaultVisibility();
  }
  try {
    const saved = window.localStorage.getItem(VISIBILITY_KEY);
    if (!saved) {
      return defaultVisibility();
    }
    const parsed = JSON.parse(saved) as VisibilityState;
    if (
      parsed.TBPX?.length === 4
      && parsed.TFPX?.length === 8
      && parsed.TEPX?.length === 4
      && parsed.TBPXParts?.length === 4
      && parsed.TFPXParts?.length === 4
      && parsed.TEPXParts?.length === 4
    ) {
      return parsed;
    }
  } catch {
    // Fall back to all-visible state if storage is unavailable or invalid.
  }
  return defaultVisibility();
}

function detailUrl(
  uid: string,
  module: ModuleDescriptor,
  hardwareKeys: string[],
  chipIndex?: number
): string {
  const params = new URLSearchParams();
  const firstHardware = hardwareKeys[0]?.split('/');
  if (firstHardware?.length === 3) {
    params.set('var-board', firstHardware[0]);
    params.set('var-optical_group', firstHardware[1]);
    params.set('var-hybrid', firstHardware[2]);
    params.set('var-chip', chipIndex === undefined ? 'All' : String(chipIndex));
  }
  params.set('var-subdetector', module.subdetector);
  if (module.layer !== undefined) {
    params.set('var-layer', String(module.layer));
    params.set('var-ladder', String(module.ladder));
    params.set('var-z_side', String(module.zSide));
  } else {
    params.set('var-detector_side', String(module.side));
    params.set('var-disk', String(module.disk));
    params.set('var-ring', String(module.ring));
    params.set('var-half', String(module.half));
  }
  params.set('var-module', String(module.moduleIndex));
  params.set('var-return_url', window.location.href);
  params.set('from', 'now-15m');
  params.set('to', 'now');
  return `/d/${encodeURIComponent(uid)}/${encodeURIComponent(uid)}?${params.toString()}`;
}

export const InnerTracker3DPanel = ({
  data,
  options,
  replaceVariables,
}: PanelProps<InnerTracker3DOptions>) => {
  const effectiveOptions = useMemo(
    () => {
      const merged = { ...DEFAULT_OPTIONS, ...options };
      // Migrate dashboards generated by the initial release, whose no-data
      // colour was nearly indistinguishable from Grafana's dark background.
      if (
        !merged.noDataColor
        || ['#252a32', '#68758a', '#111820'].includes(merged.noDataColor.toLowerCase())
      ) {
        merged.noDataColor = DEFAULT_OPTIONS.noDataColor;
      }
      const register = replaceVariables('${register}');
      const automaticLimits = REGISTER_LIMITS[register];
      merged.lowerLimit = effectiveRegisterLimit(
        replaceVariables('${low_limit}'),
        automaticLimits?.lower
      );
      merged.upperLimit = effectiveRegisterLimit(
        replaceVariables('${high_limit}'),
        automaticLimits?.upper
      );
      return merged;
    },
    [options, replaceVariables]
  );
  const hostRef = useRef<HTMLDivElement>(null);
  const sceneRef = useRef<DetectorScene>();
  const [hovered, setHovered] = useState<HoveredModule>();
  const [cameraMode, setCameraMode] = useState<CameraMode>('rotate');
  const [beamPipeVisible, setBeamPipeVisible] = useState(true);

  useEffect(() => {
    const register = replaceVariables('${register}');
    const defaults = REGISTER_LIMITS[register];
    const rawLow = replaceVariables('${low_limit}');
    const rawHigh = replaceVariables('${high_limit}');
    const updates: Record<string, string> = {};
    if (rawLow.trim().toLowerCase() === 'auto') {
      updates['var-low_limit'] = defaults?.lower === undefined
        ? 'None'
        : String(defaults.lower);
    }
    if (rawHigh.trim().toLowerCase() === 'auto') {
      updates['var-high_limit'] = defaults?.upper === undefined
        ? 'None'
        : String(defaults.upper);
    }
    if (Object.keys(updates).length > 0) {
      locationService.partial(updates, true);
    }
  }, [replaceVariables]);
  const [visibility, setVisibility] = useState<VisibilityState>(() =>
    loadVisibility(effectiveOptions.rememberVisibility)
  );

  const modules = useMemo(
    () => buildDetectorGeometry(geometryFromJson(effectiveOptions.geometryOverridesJson)),
    [effectiveOptions.geometryOverridesJson]
  );
  const measurements = useMemo(
    () => mapMeasurementsToModules(
      data,
      modules,
      effectiveOptions.hardwareMappingJson,
      effectiveOptions.aggregation
    ),
    [data, modules, effectiveOptions.hardwareMappingJson, effectiveOptions.aggregation]
  );
  const detailsUidRef = useRef(effectiveOptions.detailsDashboardUid);

  useEffect(() => {
    detailsUidRef.current = effectiveOptions.detailsDashboardUid;
  }, [effectiveOptions.detailsDashboardUid]);

  const selectModule = useCallback((
    module: ModuleDescriptor,
    chipIndex: number,
    measurement?: ModuleMeasurement
  ) => {
    // Without a hardware key the details dashboard cannot be filtered and
    // would misleadingly show every board/hybrid at once.
    if (!measurement?.hardwareKeys.length) {
      return;
    }
    window.location.href = detailUrl(
      detailsUidRef.current,
      module,
      measurement.hardwareKeys,
      chipIndex
    );
  }, []);

  useEffect(() => {
    if (!hostRef.current) {
      return;
    }
    const scene = new DetectorScene(hostRef.current, modules, effectiveOptions, {
      onHover: setHovered,
      onSelect: selectModule,
    });
    sceneRef.current = scene;
    scene.setVisibility(visibility);
    scene.setCameraMode(cameraMode);
    scene.setBeamPipeVisible(beamPipeVisible);
    scene.updateMeasurements(measurements);
    return () => {
      scene.dispose();
      sceneRef.current = undefined;
    };
    // Scene recreation is limited to topology or navigation changes.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [modules, selectModule]);

  useEffect(() => {
    sceneRef.current?.updateOptions(effectiveOptions);
  }, [effectiveOptions]);

  useEffect(() => {
    sceneRef.current?.updateMeasurements(measurements);
  }, [measurements]);

  useEffect(() => {
    sceneRef.current?.setVisibility(visibility);
    if (effectiveOptions.rememberVisibility) {
      try {
        window.localStorage.setItem(VISIBILITY_KEY, JSON.stringify(visibility));
      } catch {
        // The panel remains usable when local storage is blocked.
      }
    }
  }, [visibility, effectiveOptions.rememberVisibility]);

  useEffect(() => {
    sceneRef.current?.setCameraMode(cameraMode);
  }, [cameraMode]);

  useEffect(() => {
    sceneRef.current?.setBeamPipeVisible(beamPipeVisible);
  }, [beamPipeVisible]);

  const visibleElements =
    visibility.TBPX.filter(Boolean).length
    + visibility.TFPX.filter(Boolean).length
    + visibility.TEPX.filter(Boolean).length;
  const visibleSections =
    visibility.TBPXParts.filter(Boolean).length
    + visibility.TFPXParts.filter(Boolean).length
    + visibility.TEPXParts.filter(Boolean).length;
  const lowLabel = effectiveOptions.lowerLimit === undefined
    ? 'None'
    : String(effectiveOptions.lowerLimit);
  const highLabel = effectiveOptions.upperLimit === undefined
    ? 'None'
    : String(effectiveOptions.upperLimit);

  return (
    <div className="cmsit3d-root">
      <VisibilityTree
        value={visibility}
        onChange={setVisibility}
        onResetCamera={() => sceneRef.current?.resetCamera()}
        cameraMode={cameraMode}
        onCameraModeChange={setCameraMode}
        beamPipeVisible={beamPipeVisible}
        onBeamPipeVisibleChange={setBeamPipeVisible}
      />
      <main className="cmsit3d-viewport">
        <div ref={hostRef} className="cmsit3d-canvas" />
        <div className="cmsit3d-status">
          <span>{visibleElements}/16 elements, {visibleSections}/12 sections visible</span>
          <span>{measurements.size}/{modules.length} modules with data</span>
        </div>
        <div className="cmsit3d-legend">
          <span>Limits: {lowLabel} – {highLabel}</span>
          <span><i style={{ background: effectiveOptions.goodColor }} />Within limits</span>
          <span><i style={{ background: effectiveOptions.badColor }} />Outside limits</span>
          <span><i style={{ background: effectiveOptions.noDataColor }} />No data</span>
        </div>
      </main>
      <Tooltip hovered={hovered} />
    </div>
  );
};
